spring.application.name=JPay
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-null-for-primitives=true
spring.jackson.default-property-inclusion=non_null
spring.mvc.problemdetails.enabled=true
spring.web.resources.add-mappings=false
