spring.application.name=JPay
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.mvc.problemdetails.enabled=true
jpay.shared.enabled=true
jpay.shared.notifications.enabled=true
jpay.shared.notifications.source=jpay
springdoc.paths-to-match=/api/v1/**
springdoc.override-with-generic-response=false
